# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check statement coverage of git diff
      run: |
        set -x

        # 1. git diff for this PR
        git fetch origin
        git diff origin/${GITHUB_BASE_REF} > branch.diff
        
        # 2. Run coverage report (optionally pass --sources).
        coverage run -m unittest example.test

        # 3. Generate JSON from coverage report.
        coverage json

        # 4. Compare diff against coverage report.
        ./diffcoverage/diffcoverage.py -d branch.diff -r coverage.json -s example
